kind: pipeline
name: publish

trigger:
  event:
  - push
  - tag

steps:
- name: docker push branch ${DRONE_COMMIT_BRANCH}
  image: plugins/docker
  settings:
    repo: liquidinvestigations/newsleak
    tags: ${DRONE_COMMIT_BRANCH}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    cache_from: "liquidinvestigations/newsleak:latest"
  when:
    branch:
      excludes:
        - dependabot/*
    event:
    - push

- name: docker push autotag + latest
  image: plugins/docker
  settings:
    repo: liquidinvestigations/newsleak
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: secret
name: docker_username
get:
  path: liquid/ci/drone.docker
  name: username

---
kind: secret
name: docker_password
get:
  path: liquid/ci/drone.docker
  name: password
